### ISSUE TITLE
Wiki or Contributing Guide

### ISSUE THREAD

**Issue by AnmolTomer** [akashraj9828/gitstats#11]
Hi, I am interested in contributing to this awesome project 🎊. Was looking for a wiki or guidelines for contribution couldn't find one. Some good-first issues or a guide on contributing, format for opening issues etc. if you guys can make one, that would be really good, for new programmers like me. Thanks! 🙌

**Comment by akashraj9828** [comment]
Hey Anmol, Just created an contributing guide. You can contribute by first opening an issue for a feature or improvement you want and then once its assigned to you, you can make a PR on that. 
Note: dont open an PR on master. Opens PR on development branch.

**Comment by akashraj9828** [comment]
Looking forward for your amazing contribution already 🎊🎉
