### ISSUE TITLE
Consider using GitHub's GraphQL API

### ISSUE THREAD

**Issue by AliabbasMerchant** [akashraj9828/gitstats#19]
This will help save lots of data transfer and hence help speedup the app.  
For example, the current call to search the user with username 'ipfs', `https://api.github.com/search/users?q=ipfs` sends approx 32 kb of data, much of which is not needed.  
I checked, using GraphQL, the required data can be fetched in approx 3 kb, which is a 10x decrease.

**Comment by akashraj9828** [comment]
The GraphQL API has a query limit of 5k and we dont want to spend the power of graphql on searching as it would consume the quota very fast. That why we sticked to REST api for searching and used GraphQL for heavy queries only.

**Comment by AliabbasMerchant** [comment]
Okay :+1: 

By the way, you guys are using a custom (private) API for the queries, right? (Which is probably a wrapper over the GitHub API?)

**Comment by akashraj9828** [comment]
Yeah our API its just an wrapper over the GraphQL api. I have restricted the use of production api to only gitstats.me via CORS.

But you can use development api https://gitstats-api-stage.herokuapp.com for development puproses anywhere. It doesn't have CORS restrictions.
