### ISSUE TITLE
Share CTA

### ISSUE THREAD

**Issue by geekayush** [akashraj9828/gitstats#23]
Problem: The share links are good to have but they stick and take up a whole lot of space. Also, links hide behind the footer when scrolled to the bottom.

Solution: I am thinking of a single share CTA which will open a modal to let you choose among the different options available.

I would love to discuss and work upon this.

**Comment by akashraj9828** [comment]
Sounds good to me. You can work on this and open aPR implementing this once reviewed one of will merge this to master.
Note. open PR on development not master
I am assigning this to issue to you now.

**Comment by geekayush** [comment]
@akashraj9828 Can you upgrade the node engine to the latest release of version 10?

**Comment by geekayush** [comment]
@akashraj9828 I am unable to get user information. It says "User not found on Github".
Request to https://gitstats-api-stage.herokuapp.com/:username is getting scope errors.

`{"errors":[{"type":"INSUFFICIENT_SCOPES","locations":[{"line":24,"column":11}],"message":"Your token has not been granted the required scopes to execute this query. The 'email' field requires one of the following scopes: ['user:email', 'read:user'], but your token has only been granted the: ['public_repo', 'repo:invite'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens."}]}`

Can you tell me more about it?

**Comment by akashraj9828** [comment]
Hi, I changed the application token for dev server yesterday and didn't realized it didn't had proper access. I fixed it It should work as expected now. 
Let me know if you are still facing problem

**Comment by akashraj9828** [comment]
> @akashraj9828 Can you upgrade the node engine to the latest release of version 10?

Yeah we can but we dont know what will break in future if we did that. lets keep the old version of npm right now. You can use latest Node in you local dev enviorment if you want.

**Comment by geekayush** [comment]
> > @akashraj9828 Can you upgrade the node engine to the latest release of version 10?
> 
> Yeah we can but we dont know what will break in future if we did that. lets keep the old version of npm right now. You can use latest Node in you local dev enviorment if you want.

I believe nothing will break on upgrading to the latest minor release.
I'll be using 10.20.1 locally because I cannot find 10.16.x anywhere.

**Comment by akashraj9828** [comment]
Okay update the verison in your local envoirmentand build the app and if everything goes well open an PR we will update it here too.
