### ISSUE TITLE
Download PNG icon

### ISSUE THREAD

**Issue by geekayush** [akashraj9828/gitstats#24]
The download profile as PNG button looks more like a scroll button. I pressed it multiple times and then found that it's a download button rather than a scroll button.

Steps to reproduce the behaviour:
1. Go to https://gitstats.me/
2. Search for any username
3. See button at the right bottom of the screen

**Expected behaviour**
The download button should not confuse with the scroll button.

**Suggestion**
Change download icon.

**Comment by akashraj9828** [comment]
Oh dang!. Thanks for the suggestion. Would change the icon to something thats not confusing.

**Comment by akashraj9828** [comment]
I am assuming when you'll be converting the share option into modal you will handle this and make appropriate changes

**Comment by geekayush** [comment]
@akashraj9828 Yes. I'll come up with a PR solving both the issues.
