### ISSUE TITLE
Improve Responsiveness for Mobile Devices < 430px

### ISSUE THREAD

**Issue by aryanshridhar** [akashraj9828/gitstats#45]
**Describe the bug**
To Improve responsiveness for mobile devices with screen less than 430px . ( TextInput overflowing the screen )

**To Reproduce**
1. Click on Inspector and bring the website to less than 430px with the responsive tab .

**Expected behavior**
No overflowing of TextInput as shown below : 

Issue : 

![Screenshot from 2020-05-15 19-50-08](https://user-images.githubusercontent.com/53977614/82062187-5c65ab00-96e7-11ea-9df3-f9ac42c41b1c.png)

Expected Behaviour : (Iphone 5 device ~ 320px)

![Screenshot from 2020-05-15 20-03-05](https://user-images.githubusercontent.com/53977614/82062091-36d8a180-96e7-11ea-81a2-fd128f58c5f5.png)

**Desktop (please complete the following information):**
 - Browser : MF
 - Version : 76.0.1 (64-bit)

**Comment by akashraj9828** [comment]
Looks like a minor responsiveness issue. You can go ahead and open an PR on `development` branch fixing this issue. Let me know if you can do this.

Else I'll fix it when I'll get time.

**Comment by aryanshridhar** [comment]
Sure , Working on it :+1:

**Comment by akashraj9828** [comment]
Issue resolved. Hence closing this.

Thanks for contributing.  (o゜▽゜)o☆
