### ISSUE TITLE
The code has been copied from https://github.com/hereisnaman/gitfame

### ISSUE THREAD

**Issue by hereisnaman** [akashraj9828/gitstats#50]
This code has been copied from https://github.com/hereisnaman/gitfame without giving proper credits.

If the credits are not given in this repository and on the website at https://gitstats.me/ I'll have to report to take this down.

**Comment by akashraj9828** [comment]
Bro i know you did similar project and it was a good inspiration for me. 
But the code isn't copied from your repo. You can see the entire development process in commit history. The only part I referred to your repo was for a few github graphql queries for the backend nothing more.

That being said there are tons of github graphql queries that are open-sourced and it's present for free out there or I could have created just them myself too. Its not a big deal. That was a lazy work on my end. 

If you still find anything else copied directly from your repo feel free ping again.

**Comment by akashraj9828** [comment]
Hey @hereisnaman  If you haven't found any copied code then you can go ahead and delete this issue. Thanks.
