### ISSUE TITLE
Theme change on Home Page

### ISSUE THREAD

**Issue by abhinavsri360** [akashraj9828/gitstats#64]
**Is your feature request related to a problem? Please describe.**
Yes, whenever I want to change the theme of this site it is frustrating to go to the page of some user and then change the theme then go back to the home page and look at what does it look like

**Describe the solution you'd like**
A theme change button must be present at the home page as well

**Additional context**
Theme change button can be placed below the search bar

**Comment by akashraj9828** [comment]
There is no theme on Landing page. The background is Black image by default. 
I see it inverts the color when you switch the theme on profile and then go to landing page but that's not an intended feature. Will be fixing that too today. 

The color inversion will go away on reload btw.

**Comment by abhinavsri360** [comment]
Cool! btw I didn't notice that color inversion goes back on reload.
