### ISSUE TITLE
Consider adding a License

### ISSUE THREAD

**Issue by AliabbasMerchant** [akashraj9828/gitstats#9]
Hey @akashraj9828 @amirSohel007  
Great work!  
Really awesome!  
The UI, Github integration, etc everything is fantastic!

I can see lots of scope for this, and lots of further steps to take this project to great heights!
(Adding links to various commits, repos, etc; Popups with repo info; Converting this project to third person; A few UI/UX bug fixes)

I would like to become an active contributor, if it is okay with you both. I would first contribute through PRs.

**Comment by akashraj9828** [comment]
Yes, absolutely. All contributions are welcomed. And I'll add an licence in next commit. Thank you for the suggestion.

Feel free to ask us if you have any doubts about the code. Although I have placed comments in most of the places.

**Comment by akashraj9828** [comment]
If you know a bit of react/js then we were thinking of implementing a download profile as pdf/image button. The button is there in development branch in but the download function implementation is incomplete. If you could go ahead and take a shot at that we would be happy to see that.

https://github.com/akashraj9828/gitstats/blob/d64e8d45ec1b7a5551340fa02e184482fa26a2e8/src/Components/Views/Share.js#L13 
this is the funtion that needs to be completed.

**Comment by AliabbasMerchant** [comment]
Looks like you guys have already implemented the download as image feature :sweat_smile:   
I will work on some other feature/bug fix instead :+1:
