### ISSUE TITLE
Data shown incorrect

### ISSUE THREAD

**Issue by Leovaldez42** [akashraj9828/gitstats#92]
**Describe the bug**
Number of stars and repositories are shown incorrect.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a user.

**Comment by akashraj9828** [comment]
It seems to be showing correct data for me..

Can you mention the user for which you faced this issue.

**Comment by Leovaldez42** [comment]
> It seems to be showing correct data for me..
> 
> Can you mention the user for which you faced this issue.

Leovaldez42. It is showing 34 repositories while, I have only 32. 
amandesai01. His repository count is also wrong and the stars are are also incorrect. Not sure if others are facing it.

**Comment by Leovaldez42** [comment]
Leovaldez42. It is showing 34 repositories while, I have only 32.
amandesai01. His repository count is also wrong and the stars are are also incorrect. Not sure if others are facing it.

**Comment by akashraj9828** [comment]
I'm not sure why that's happening.. but github api is returning your total repos as `34`. 
This issue is not in application but in github api itself maybe.
